services:
  portainer:
    image: portainer/portainer-ce:latest
    # ports:
    #   - "9000:9091" 
    container_name: portainer
    privileged: true
    volumes:
      - portainer_data:/data
      # - /var/run/docker.sock:/var/run/docker.sock
      - /run/podman/podman.sock:/var/run/docker.sock:Z
    restart: unless-stopped
    expose:
      - 9000

  prometheus:
    image: prom/prometheus:v2.36.2
    restart: unless-stopped
    container_name: "prometheus"
    extra_hosts:
    # - abp.ql.host.com:${BACKEND_QL_IP}
      - abpql.example.com:${BACKEND_QL_IP}
    volumes:
      - ./configs/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--enable-feature=expand-external-labels'
      - '--storage.tsdb.retention.time=${RETENTION_TIME}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      # - '--web.external-url=/prometheus/'
    expose:
      - 9090
    ports:
       - 9090:9090

volumes:
  portainer_data:
  prometheus_data:
