:foreman:
  # Enable/disable foreman commands
  :enable_module: true

  # Your foreman server address
  :host: 'https://ABP_FQDN'

  # Enable using sessions
  # When sessions are enabled, hammer ignores credentials stored in the config file
  # and asks for them interactively at the begining of each session.
  :use_sessions: false
  :username: 'admin'
  :password: 'ABP_DB_PW'

  # Check API documentation cache status on each request
  :refresh_cache: false

  # API request timeout in seconds, set -1 for infinity
  :request_timeout: 120


:ssl:
  :ssl_ca_file: '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
