FROM nginx:latest

COPY ./configs/f39/repo/default.conf /etc/nginx/conf.d/default.conf

# Copy OS images into this repo container, if it needs 
RUN mkdir -p /usr/share/nginx/html/pub 
RUN chown nginx:nginx -R /usr/share/nginx 
RUN chmod 755 -R /usr/share/nginx 
