---
# Can be true, false, or http/https to enable just one of the protocols
#:enabled: https
:enabled: false

# valid providers:
#   - puppetca_hostname_whitelisting (verify CSRs based on a hostname whitelist)
#   - puppetca_token_whitelisting (verify CSRs based on a token whitelist)
:use_provider: puppetca_hostname_whitelisting

# Using 6.0 forces use of puppetca_http_api
:puppet_version: '6.0'
