---
# URL of the puppet master itself for API requests.
:puppet_url: https://PROXY_FQDN:8140
#
# SSL certificates used to access the CA API.
:puppet_ssl_ca: /etc/puppetlabs/puppet/ssl/certs/ca.pem
:puppet_ssl_cert: /etc/puppetlabs/puppet/ssl/certs/PROXY_FQDN.pem
:puppet_ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/PROXY_FQDN.pem
