---
:url: "https://ABP_FQDN"
:ssl_ca: "/etc/puppetlabs/puppetserver/ca/ca_crt.pem"
:ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/ABP_FQDN.pem"
:ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/ABP_FQDN.pem"
:puppetdir: "/opt/puppetlabs/server/data/puppetserver"
:puppetuser: "puppet"
:facts: true
:fact_extension: "json"
:timeout: 60
:report_timeout: 60
:report_retry_limit: 1
:threads: null
