# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: wanny-system'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - 'alert.rules'
# - "first.rules"
# - "second.rules"

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: "idrac-collector-combined"

    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 15s
    http_sd_configs:
      #- url: "http://abpql.example.com/monitoring/discovery"
      - url: "https://10.1.13.90/abpql/monitoring/discovery"
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # idrac-exporter is docker service name described in docker-compose file
        replacement: idrac-exporter
    metrics_path: /metrics

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: "idrac-collector-combined"

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 15s

  #   static_configs:
  #     - targets: ["10.1.13.140&identifier=555", "10.1.13.5&identifier=1"]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       # idrac-exporter is docker service name described in docker-compose file
  #       replacement: idrac-exporter
  #   metrics_path: /metrics

  # - job_name: "idrac-collector"

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 15s

  #   static_configs:
  #     - targets: ["172.26.160.1:3456"]
  #   params:
  #     target: [10.1.13.140]
  #   metrics_path: /metrics

  # - job_name: "idrac-collector2"

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 15s

  #   static_configs:
  #     - targets: ["172.26.160.1:3456"]
  #   params:
  #     target: [10.1.13.5]
  #   metrics_path: /metrics
  # - job_name: 'cadvisor'

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 15s

  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.cadvisor'
  #     type: 'A'
  #     port: 8080
#     static_configs:
#          - targets: ['cadvisor:8080']

# - job_name: 'node-exporter'

#   # Override the global default and scrape targets from this job every 5 seconds.
#   scrape_interval: 15s

#   dns_sd_configs:
#   - names:
#     - 'tasks.node-exporter'
#     type: 'A'
#     port: 9100

#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#      port: 9091

#     static_configs:
#          - targets: ['node-exporter:9100']
